In [43]:
#1. Write a Python Program to Add Two Matrices?
#ans

a = [[1,8,3],
    [4,10,6],
    [7,8,9]]

b = [[9,3,6],
    [6,10,1],
    [7,2,4]]

sum  = [[0,0,0],
     [0,0,0],
     [0,0,0]]

for i in range(len(a)):
    for j in range(len(a[0])):
        sum[i][j] = a[i][j] + b[i][j]
print("For the given matrix %s and %s the sum is"%(a,b))        
for s in sum:
    print(s)
    
#2nd method using numpy
import numpy as np
x = [[1,8,3],
    [4,10,6],
    [7,8,9]]

y = [[9,3,6],
    [6,10,1],
    [7,2,4]]

sum1 = (np.array(x) + np.array(y))
print("\n Using numpy the sum for same given matrix is \n",sum1)

For the given matrix [[1, 8, 3], [4, 10, 6], [7, 8, 9]] and [[9, 3, 6], [6, 10, 1], [7, 2, 4]] the sum is
[10, 11, 9]
[10, 20, 7]
[14, 10, 13]

 Using numpy the sum for same given matrix is 
 [[10 11  9]
 [10 20  7]
 [14 10 13]]


In [58]:
#2. Write a Python Program to Multiply Two Matrices?
#ans

a = [[1,8,3],
    [4,10,6],
    [7,8,9]]

b = [[9,3,6],
    [6,10,1],
    [7,2,4]]

mul= [[0,0,0],
     [0,0,0],
     [0,0,0]]

for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            mul[i][j] += a[i][k]* b[k][j]
print("For the given matrix %s and %s the matrix multiplication is"%(a,b))        
for s in mul:
    print(s)
    
    
#2nd method using numpy
import numpy as np
x = [[1,8,3],
    [4,10,6],
    [7,8,9]]

y = [[9,3,6],
    [6,10,1],
    [7,2,4]]

mul1 = np.dot(x,y)
print("\n Using numpy the multiplication for same given matrix is \n",mul1) 



For the given matrix [[1, 8, 3], [4, 10, 6], [7, 8, 9]] and [[9, 3, 6], [6, 10, 1], [7, 2, 4]] the matrix multiplication is
[78, 89, 26]
[138, 124, 58]
[174, 119, 86]

 Using numpy the multiplication for same given matrix is 
 [[ 78  89  26]
 [138 124  58]
 [174 119  86]]


In [75]:
#3. Write a Python Program to Transpose a Matrix?
#ans
import numpy 
a = [[1,2,3],
    [4,5,6],
    [7,8,9],
    [1,1,1]]
transpose = [[a[j][i]
           for j in range(len(a))] for i in range(len(a[0]))]
print("The transpose of the matrix %s is \n %s"%(a,transpose))

print(" \n Using numpy the result is : \n" , numpy.transpose(matrix))


The transpose of the matrix [[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 1, 1]] is 
 [[1, 4, 7, 1], [2, 5, 8, 1], [3, 6, 9, 1]]
 
 Using numpy the result is : 
 [[1 4 7 1]
 [2 5 8 1]
 [3 6 9 1]]


In [89]:
#4. Write a Python Program to Sort Words in Alphabetic Order?
#ans

str = input("Enter a string : ")
sw = [s.lower() for s in str.split()]
sw.sort()
print("The sorted words are : ",' '.join(sw))

Enter a string : I am solving A Ineuron python programmING assignment
The sorted words are :  a am assignment i ineuron programming python solving


In [92]:
#5. Write a Python Program to Remove Punctuation From a String?
#ans

sym = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
op_str =""
ip_str = input("enter a string to remove punctuation marks : ")
for i in ip_str:
    if i not in sym:
        op_str+= i
print("The string without any punctuation marks : ",op_str)

enter a string to remove punctuation marks : The sound was beeped out with captions $%@%^*$%$%^# . It was hard to understand.
The string without any punctuation marks :  The sound was beeped out with captions   It was hard to understand
